
POST {{host}}/api/login
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_SESSION

{
  "username": "username",
  "password": "password"
}

###
POST {{host}}/api/login
Content-Type: application/x-www-form-urlencoded
Cookie: XDEBUG_SESSION=XDEBUG_SESSION

username=username&password=password


###
POST {{host}}/api/login
Accept: application/json

{
    "grant_type" : "client_credentials",
    "client_id" : "0001".
  client_secret with the client's secret.
scope with a space-delimited list of requested scope permissions.
}


